app:
  name: "match"
strings:
  ru:
    enter_players_prompt: "Отметьте всех игроков, участвовавших в матче, используя формат @username (одним сообщением всех игроков)."
    no_players_found: "В вашем сообщении не найдено игроков. Пожалуйста, отметьте игроков, используя формат @username."
    upload_screenshot_prompt: "Пришлите скриншот итогов матча. Нажмите PrintScreen (PrtSc) в игре, затем вставьте (Ctrl+V) сюда."
    hero_selection_instructions: "Укажите, какого героя использовал каждый игрок."
    enter_hero_format: "Введите выбор героев в формате:\n@username1: Имя Героя\n@username2: Другой Герой\n..."
    hero_selection_error: "Ошибка при обработке выбора героев. Пожалуйста, попробуйте снова в правильном формате."
    select_winner_prompt: "Кто победил? Упомяните игрока через @"
    select_win_type: "Какой тип победы был достигнут?"
    match_summary: "Итоги матча"
    players_label: "Игроки:"
    win_type_label: "Тип победы"
    confirm_button: "Подтвердить и сохранить"
    screenshot_preview_error: "Не удалось загрузить предпросмотр скриншота."
    match_recorded_success: "✅ Матч успешно записан!"
    match_id: "ID матча"
    date: "Дата"
    win_type: "Тип победы"
    participants: "Участники"
    return_to_menu: "Возвращение в главное меню."
    match_save_error: "Ошибка при сохранении матча. Пожалуйста, попробуйте снова."
    match_cancelled: "Запись матча отменена."
    process_cancelled: "Отмена"
    cancel: "Назад"
    invalid_players_count: "Недостаточно игроков для записи матча. Пожалуйста, попробуйте снова."
    winner_not_in_players: "Победитель не найден в списке игроков. Пожалуйста, попробуйте снова."
    match_timeout: "Время на ввод истекло. Возвращение в главное меню."