app:
  name: "clanrating"
strings:
  ru:
    clan_not_found: "Клан не найден. Пожалуйста, выберите клан из списка."
    error: "Произошла ошибка при получении статистики клана. Пожалуйста, попробуйте позже."
    exit_message: "Вы вышли из режима просмотра рейтингов кланов."
    welcome_message: "Какой клан вас интересует? Если вы закончили, нажмите кнопку выхода"
    goodbye_message: "До свидания!"