strings:
  ru:
    title_prompt: "Какой титул вы желаете изменить?"
    not_eligible: "Вы недостойны титула"
    title_saved: "Титул сохранен"
    enter_title: "Введите новое название титула"
    title_too_long: "Титул слишком длинный. Пожалуйста, используйте не более 50 символов."
    title_updated: "Титул обновлен"