strings:
  ru:
    select_top_type: "Какой топ-лист вас интересует?"
    top_players_overall_header: "Топ-10 игроков по общему рейтингу"
    top_players_by_hero_header: "Топ-10 игроков на герое {hero_name}"
    top_players_by_clan_header: "Топ-10 игроков клана {clan_name}"
    top_heroes_header: "Топ-24 героев по общему рейтингу"
    top_clans_header: "Топ-6 кланов по общему рейтингу"
    top_players_explanation: "Числа после никнейма означают: @имяигрока – общий рейтинг: победы-поражения-винрейт"
    enter_hero_name: "Введите имя героя, используя «Ответить» на это сообщение"
    select_clan: "Какой клан вас интересует?"
    hero_not_found: "Герой не найден. Пожалуйста, введите корректное имя героя."
    clan_not_found: "Клан не найден. Пожалуйста, попробуйте снова."
    goodbye: "До свидания!"
    timeout: "Сессия завершена из-за отсутствия активности."